[package]
name = "cs496"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automata = "0.0.4"
bitvec = "1"
crossbeam = "0.8.2"
lazy_static = "1.4.0"
petgraph = "0.6.3"
strum = "0.24"
strum_macros = "0.24"
xml-rs = "0.8.4"
serde_json = "1.0"
serde = { version = "1.0.160", features = ["derive"] }
rand = "0.8.5"

[profile.release]
debug = true